Repository csunibo/informabot, pull requests merged in 2021-09, with the labels that each got.

#1 Json
  actions.json
  index.js
  memes.json
Labels: enhancement

#2 Groups
  README.md
  index.js
  json/actions.json
  json/groups.json
Labels: enhancement

#3 feat: tweak help command
  .gitignore
  index.js
  json/actions.json
Labels: documentation

#4 New meme
  json/memes.json
Labels: good first issue
